import os
pathSep = os.path.sep
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 600
NEW_SCREEN_WIDTH = SCREEN_WIDTH/4
NEW_SCREEN_HEIGHT = SCREEN_HEIGHT/4

WINDOW_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT
NEW_WINDOW_SIZE = NEW_SCREEN_WIDTH, NEW_SCREEN_HEIGHT